# Action 名稱
name: Deploy
# 觸發時機，當推送到分支 master 時
on:
  push:
    branches: [ master ]
# 執行的工作
jobs:
  # 工作名稱
  deploy:
    # 執行工作的虛擬機作業系統
    runs-on: ubuntu-latest
    # 工作步驟
    steps:
      # 步驟一：複製程式碼
      - name: checkout
        # 使用的 actions/checkout 複製程式碼
        uses: actions/checkout@master

      # 步驟二：編譯及部署
      - name: buildAndDeploy
        uses: JamesIves/github-pages-deploy-action@master 
        # 步驟設定
        env:
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
          # 使用 master 分支的檔案
          BASE_BRANCH: master
          # 部署到 gh-pages 分支
          BRANCH: gh-pages
          # 編譯後要上傳的資料夾
          FOLDER: dist
          # 執行指令
          BUILD_SCRIPT: npm install && npm run build
          # 動作完成後清除檔案
          CLEAN: true
          VUE_APP_API: ${{ secrets.VUE_APP_API }}